'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Namespace APSA_2

    Partial Public Class Entities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=Entities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
    
        Public Overridable Function AD_SP_VALIDACOES_ESTRUTURAIS() As ObjectResult(Of AD_SP_VALIDACOES_ESTRUTURAIS_Result)
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of AD_SP_VALIDACOES_ESTRUTURAIS_Result)("AD_SP_VALIDACOES_ESTRUTURAIS")
        End Function
    
    End Class

End Namespace
