'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Namespace Apsa2

    Partial Public Class ARQUIVO_DIGITALEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=ARQUIVO_DIGITALEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
    
        Public Overridable Function AD_ATUALIZA_SITUACAO_CLIENTES() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AD_ATUALIZA_SITUACAO_CLIENTES")
        End Function
    
        Public Overridable Function AD_CARREGA_CONDOMINIO(cNPJ As String) As Integer
            Dim cNPJParameter As ObjectParameter = If(cNPJ IsNot Nothing, New ObjectParameter("CNPJ", cNPJ), New ObjectParameter("CNPJ", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AD_CARREGA_CONDOMINIO", cNPJParameter)
        End Function
    
        Public Overridable Function AD_CRI_CONDOMINIOS_COM_LANCAMENTO_INATIVO() As ObjectResult(Of AD_CRI_CONDOMINIOS_COM_LANCAMENTO_INATIVO_Result)
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of AD_CRI_CONDOMINIOS_COM_LANCAMENTO_INATIVO_Result)("AD_CRI_CONDOMINIOS_COM_LANCAMENTO_INATIVO")
        End Function
    
        Public Overridable Function AD_CRI_CONDOMINIOS_SEM_CNPJ() As ObjectResult(Of AD_CRI_CONDOMINIOS_SEM_CNPJ_Result)
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of AD_CRI_CONDOMINIOS_SEM_CNPJ_Result)("AD_CRI_CONDOMINIOS_SEM_CNPJ")
        End Function
    
        Public Overridable Function AD_CRI_CONDOMINIOS_SEM_LANCAMENTOS(agencia As Nullable(Of Integer), conta As Nullable(Of Integer), origem As String, competencia As Nullable(Of Integer)) As Integer
            Dim agenciaParameter As ObjectParameter = If(agencia.HasValue, New ObjectParameter("Agencia", agencia), New ObjectParameter("Agencia", GetType(Integer)))
    
            Dim contaParameter As ObjectParameter = If(conta.HasValue, New ObjectParameter("Conta", conta), New ObjectParameter("Conta", GetType(Integer)))
    
            Dim origemParameter As ObjectParameter = If(origem IsNot Nothing, New ObjectParameter("Origem", origem), New ObjectParameter("Origem", GetType(String)))
    
            Dim competenciaParameter As ObjectParameter = If(competencia.HasValue, New ObjectParameter("Competencia", competencia), New ObjectParameter("Competencia", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AD_CRI_CONDOMINIOS_SEM_LANCAMENTOS", agenciaParameter, contaParameter, origemParameter, competenciaParameter)
        End Function
    
        Public Overridable Function AD_DROPA_TABELAS_TEMPORARIAS() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AD_DROPA_TABELAS_TEMPORARIAS")
        End Function
    
        Public Overridable Function AD_FORNECEDORES_SP(contaCliente As String, competencia As Nullable(Of Integer)) As ObjectResult(Of AD_FORNECEDORES_SP_Result)
            Dim contaClienteParameter As ObjectParameter = If(contaCliente IsNot Nothing, New ObjectParameter("ContaCliente", contaCliente), New ObjectParameter("ContaCliente", GetType(String)))
    
            Dim competenciaParameter As ObjectParameter = If(competencia.HasValue, New ObjectParameter("competencia", competencia), New ObjectParameter("competencia", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of AD_FORNECEDORES_SP_Result)("AD_FORNECEDORES_SP", contaClienteParameter, competenciaParameter)
        End Function
    
        Public Overridable Function AD_GERA_XML_GESTORES(cNPJ As String, cOMPETENCIA As Nullable(Of Integer)) As ObjectResult(Of AD_GERA_XML_GESTORES_Result)
            Dim cNPJParameter As ObjectParameter = If(cNPJ IsNot Nothing, New ObjectParameter("CNPJ", cNPJ), New ObjectParameter("CNPJ", GetType(String)))
    
            Dim cOMPETENCIAParameter As ObjectParameter = If(cOMPETENCIA.HasValue, New ObjectParameter("COMPETENCIA", cOMPETENCIA), New ObjectParameter("COMPETENCIA", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of AD_GERA_XML_GESTORES_Result)("AD_GERA_XML_GESTORES", cNPJParameter, cOMPETENCIAParameter)
        End Function
    
        Public Overridable Function AD_INDICES() As ObjectResult(Of Nullable(Of Integer))
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("AD_INDICES")
        End Function
    
        Public Overridable Function Extrator_AD_B_Cadastro_De_Empregados() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_B_Cadastro_De_Empregados")
        End Function
    
        Public Overridable Function Extrator_AD_B_Folha_De_Pagamento(competencia As Nullable(Of Integer)) As Integer
            Dim competenciaParameter As ObjectParameter = If(competencia.HasValue, New ObjectParameter("Competencia", competencia), New ObjectParameter("Competencia", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_B_Folha_De_Pagamento", competenciaParameter)
        End Function
    
        Public Overridable Function Extrator_AD_C_Cadastro_De_Sindico(competencia As String) As Integer
            Dim competenciaParameter As ObjectParameter = If(competencia IsNot Nothing, New ObjectParameter("Competencia", competencia), New ObjectParameter("Competencia", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Cadastro_De_Sindico", competenciaParameter)
        End Function
    
        Public Overridable Function Extrator_AD_C_Centro_De_Custo() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Centro_De_Custo")
        End Function
    
        Public Overridable Function Extrator_AD_C_Fluxo_De_Caixa() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Fluxo_De_Caixa")
        End Function
    
        Public Overridable Function Extrator_AD_C_Identificacao_Condominio(agencia As Nullable(Of Integer), conta As Nullable(Of Integer)) As Integer
            Dim agenciaParameter As ObjectParameter = If(agencia.HasValue, New ObjectParameter("agencia", agencia), New ObjectParameter("agencia", GetType(Integer)))
    
            Dim contaParameter As ObjectParameter = If(conta.HasValue, New ObjectParameter("conta", conta), New ObjectParameter("conta", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Identificacao_Condominio", agenciaParameter, contaParameter)
        End Function
    
        Public Overridable Function Extrator_AD_C_Lancamento(competencia As Nullable(Of Integer)) As Integer
            Dim competenciaParameter As ObjectParameter = If(competencia.HasValue, New ObjectParameter("Competencia", competencia), New ObjectParameter("Competencia", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Lancamento", competenciaParameter)
        End Function
    
        Public Overridable Function Extrator_AD_C_Plano_De_Contas() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Plano_De_Contas")
        End Function
    
        Public Overridable Function Extrator_AD_C_Saldo(competencia As String) As Integer
            Dim competenciaParameter As ObjectParameter = If(competencia IsNot Nothing, New ObjectParameter("Competencia", competencia), New ObjectParameter("Competencia", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Saldo", competenciaParameter)
        End Function
    
        Public Overridable Function Extrator_AD_C_Unidades(competencia As String) As Integer
            Dim competenciaParameter As ObjectParameter = If(competencia IsNot Nothing, New ObjectParameter("Competencia", competencia), New ObjectParameter("Competencia", GetType(String)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_C_Unidades", competenciaParameter)
        End Function
    
        Public Overridable Function Extrator_AD_D_Documentos() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_D_Documentos")
        End Function
    
        Public Overridable Function Extrator_AD_D_Paginas() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_D_Paginas")
        End Function
    
        Public Overridable Function Extrator_AD_M_Cadastro_De_Sindico() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_M_Cadastro_De_Sindico")
        End Function
    
        Public Overridable Function Extrator_AD_M_Centro_De_Custo() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_M_Centro_De_Custo")
        End Function
    
        Public Overridable Function Extrator_AD_M_Fluxo_De_Caixa() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_M_Fluxo_De_Caixa")
        End Function
    
        Public Overridable Function Extrator_AD_M_Identificacao_Condominio() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_M_Identificacao_Condominio")
        End Function
    
        Public Overridable Function Extrator_AD_M_Lancamento() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_M_Lancamento")
        End Function
    
        Public Overridable Function Extrator_AD_M_Plano_De_Contas() As Integer
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_M_Plano_De_Contas")
        End Function
    
        Public Overridable Function Extrator_AD_M_Saldo(competencia As Nullable(Of Integer)) As Integer
            Dim competenciaParameter As ObjectParameter = If(competencia.HasValue, New ObjectParameter("Competencia", competencia), New ObjectParameter("Competencia", GetType(Integer)))
    
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("Extrator_AD_M_Saldo", competenciaParameter)
        End Function
    
        Public Overridable Function AD_RETORNA_VALIDACOES_ESTRUTURAIS() As ObjectResult(Of AD_RETORNA_VALIDACOES_ESTRUTURAIS_Result)
            Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of AD_RETORNA_VALIDACOES_ESTRUTURAIS_Result)("AD_RETORNA_VALIDACOES_ESTRUTURAIS")
        End Function
    
    End Class

End Namespace
